post http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Integrating Prettier + ESLint + Airbnb Style Guide in VSCode",
    "author": "Jeffrey Zhen",
    "url": "https://blog.echobind.com/integrating-prettier-eslint-airbnb-style-guide-in-vscode-47f07b5d7d6a",
    "likes": 58
}