post http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "The 10 Component Commandments",
    "author": "selbekk",
    "url": "https://dev.to/selbekk/the-10-component-commandments-2a7f",
    "likes": 58
}